spring.application.name=ragassistant

spring.datasource.url=jdbc:postgresql://localhost:5433/rag_assistant
spring.datasource.username=rag_user
spring.datasource.password=rag_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

openai.api.key=${OPENAI_API_KEY}